spring:
  application:
    name: practice
  datasource:
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username : sa
      password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: localhost:19002                                          # Kafka 접속 정보 지정
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer    # 문자열 형태로 메시지 키 값 직렬화
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer  # 문자열 형태로 메시지 값 직렬화
    consumer:
      group-id: practice
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer      # 문자열 형태로 메시지 키 값 역직렬화
      value-deserializer: org.apache.kafka.common.serialization.JsonDeserializer    # 문자열 형태로 메시지 값 역직렬화
